# Site
repository: https://mr-rahimi.github.io
# favicon: images/favicon.ico

# Personal info
name: Mohammad Reza Rahimi
title: Full-Stack .NET Developer
email: mr_rahimi@live.com
website: https://mr-rahimi.github.io

# Social links
github_username:  mr-rahimi
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: mrrahimi
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # Software Developer with several years of experience as .NET, ASP.NET and Front-end developer.
I have been working since 2009 as a Software Developer. I am passionate about do my task in the best way and in reasonable time.
I would not hesitate to learn new technology if I am sure that it helps me to do my tasks in better manner.  

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
